---
title: "Team3-Project1"
author: "Muhannad Alwhebie, Liang Gao, Nammin Woo"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    number_sections: false
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, message = F)
options(scientific=T, digits = 3) 
```

```{r}
Robbery = data.frame(read.csv("Robbery_DC_clean.csv"))
head(Robbery,5)
tail(Robbery,5)
str(Robbery)
```

```{r}
mean(Robbery$Month,na.rm = TRUE)
sd(Robbery$Month, na.rm = TRUE)
var(Robbery$Month, na.rm = TRUE)
```

```{r}
mean(Robbery$Date,na.rm = TRUE)
sd(Robbery$Date, na.rm = TRUE)
var(Robbery$Date, na.rm = TRUE)
```

```{r}
mean(Robbery$Day_cat,na.rm = TRUE)
sd(Robbery$Day_cat, na.rm = TRUE)
var(Robbery$Day_cat, na.rm = TRUE)
```

```{r}
mean(Robbery$DISTRICT,na.rm = TRUE)
sd(Robbery$DISTRICT, na.rm = TRUE)
var(Robbery$DISTRICT, na.rm = TRUE)
```

```{r}
ggplot(data=Robbery, aes(Month)) + 
  geom_histogram(col="red", 
                 fill="blue", 
                 alpha = .7) + 
  labs(x="Month", y="Frequency") +
  labs(title="Monthly crime frequency")
```

```{r}
ggplot(data=Robbery, aes(Year)) + 
  geom_histogram(col="red", 
                 fill="blue", 
                 alpha = .7) + 
  labs(x="Year", y="Frequency") +
  labs(title="Yearly crime frequency")
```
```{r}
ggplot(data=Robbery, aes(Day_cat)) + 
  geom_histogram(col="red", 
                 fill="blue", 
                 alpha = .7) + 
  labs(x="Day_cat", y="Frequency") +
  labs(title="Dayily crime frequency")
```
```{r}
ggplot(data=Robbery, aes(DISTRICT)) + 
  geom_histogram(col="red", 
                 fill="blue", 
                 alpha = .7) + 
  labs(x="DISTRICT", y="Frequency") +
  labs(title="Crime frequency in different Districts")
```

